apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ssanchez4/api-app:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "350m"
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
