apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patrones-charts
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://nexus.146.190.187.99.nip.io/repository/helm-repo/
    targetRevision: '>=0.1.0'    # Esto seleccionará la versión más reciente que sea mayor a 0.1.0
    chart: chartpatrones
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true