apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "api-service" }}
  labels:
    {{- include "chartpatrones.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: api
